### ISSUE TITLE
AAAR doesn't work with a proxy

### ISSUE THREAD

**Issue by fcorti** [fcorti/alfresco-audit-analysis-reporting#14]
From issue https://github.com/fcorti/alfresco-audit-analysis-reporting/issues/13

AAAR (or CTools) always use the port number that Tomcat is running on. Don't pass AAAR through a proxy. As soon as I targeted port 8080 (7080 for me), AAAR came up.

I think this is happening because javascripts cannot access data across different domains; in this case http://myserver/pentaho and http://myserver:7080/pentaho are technically different domains. I am not sure where a port number is being used in your code (or in CDE), but it should really respect the settings in tomcat/webapps/pentaho/WEB-INF/web.xml and tomcat/config/server.xml. At any rate, the result is broken AAAR.

**Comment by digcat** [comment]
just wondering how we can help on this, Ill try and spin up the pentaho side of things, as Honeycomb has a reverse proxy in place, and your addon is installed, on the dev-1.1 branch of honeycomb.

**Comment by fcorti** [comment]
Hi Digicat, I would like to start working on it.
I'll keep informed here or tell me if you prefer to be informed directly.
Many thanks for the support.

**Comment by digcat** [comment]
hi fcorti yes no stress, i see these tickets fine.  Do you have a recipe for the pentaho side of things, when running on own server, so we can setup in a standard correct way?

**Comment by fcorti** [comment]
Do you refer to correctly set Pentaho with a proxy?
In the link below the instructions:
http://pedroalves-bi.blogspot.it/2014/07/using-pentaho-marketplace-over-proxy-or.html

**Comment by fcorti** [comment]
Test: Pentaho with reverse proxy
On a Pentaho BA server, I installed apache2 with mod_proxy.
`sudo apt-get install apache2`
`sudo a2enmod proxy_http`
`sudo service apache2 restart`
Then I develop a fool example with a reverse proxy from port 80 to 8180 on localhost.
`sudo nano /etc/apache2/mods-enabled/proxy.conf`
`<VirtualHost *:80>`
`  ProxyPreserveHost On`
`  ProxyRequests Off` 
`  ProxyPass / http://localhost:8180/` 
`  ProxyPassReverse / http://localhost:8180/` 
`</VirtualHost>`
`sudo service apache2 restart`
Accessing to AAAR and Pentaho using `http://<ip>` everything works properly.
@digcat: could add some comments describing your test case?
Using my test case everything seems to work properly.
Many thanks.

**Comment by digcat** [comment]
Hi Francesco

Sorry been flat out, will revisit this shortly,

cheers

Daren

**Comment by fcorti** [comment]
Great, I'll stay tuned and available to test it once more time.
Thanks.

**Comment by fcorti** [comment]
After tests, no limitations appeared.
