### ISSUE TITLE
Update button into the marketplace

### ISSUE THREAD

**Issue by fcorti** [fcorti/alfresco-audit-analysis-reporting#19]
Even if you install the AAAR 3 the update button is active.
Pressing the button the AAAR 2.4 version is installed.
This should be avoid.

**Comment by bmejias** [comment]
Don't click on the "Update" button
![aaar-3 0-update](https://cloud.githubusercontent.com/assets/606453/6980954/5aa43f70-d9fa-11e4-9eb6-e86ed9d1b8ad.png)

**Comment by fcorti** [comment]
Unfortunately this is the Pentaho behaviour when more than one versions are available for the same version.
I think I will submit to the Pentaho team attention as an issue.
