### ISSUE TITLE
Loosing Alfresco menu bar in AAAR installation v4.3

### ISSUE THREAD

**Issue by vurquia** [fcorti/alfresco-audit-analysis-reporting#36]
Environment:
SO Windows
Alfresco 5.1 CE
AAAR-Alfresco-CE-v5.1-Repository-v4.3.amp
AAAR-Alfresco-CE-v5.1-Share-v4.3.amp

**Comment by vurquia** [comment]
An image, I tested v4.4 on dev and has the same problem :( 

![aaar problem](https://cloud.githubusercontent.com/assets/8777267/16844369/c65a4bd0-49dc-11e6-8f3d-88e28cac7aa1.JPG)

**Comment by fcorti** [comment]
Hi, I'm sure v4.4 has the same problem because the Share AMP didn't change from 4.3.
I'll go through this bug asap... thank you for your submission and back to you soon.

**Comment by fcorti** [comment]
Great job Younes.
Thank you for your contribution.
