### ISSUE TITLE
Question Pentaho Port 

### ISSUE THREAD

**Issue by rootinshell** [fcorti/alfresco-audit-analysis-reporting#49]
My pentaho server is running on 8082. where can i configure the AAAR Dashlet links ? because now is redirecting to 8080.

Regards.

**Comment by yregaieg** [comment]
Have gone through this : http://fcorti.com/alfresco-audit-analysis-reporting/aaar-advanced-configurations/alfresco-menu-to-aaar/ 

I does provide quite a few config options that may cover your requirements !

**Comment by rootinshell** [comment]
Thanks my requirements were covered indeed :)
l3ez  !
