### ISSUE TITLE
Extraction failing on NODES STAGING

### ISSUE THREAD

**Issue by shabanash** [fcorti/alfresco-audit-analysis-reporting#52]
HI Francesco  ,

Greetings ... 

I am a newbie to the Alfresco and AAAR plat Form . I tried configuring the AAAR and faced below challenge .

PlatForm  :- Ubuntu 18.04
Alfresco Version :- Alfresco Platform  5.2.g  &  Alfresco Share  5.2.f
AAAR Version :- AAAR_v4.5.zip
Amp Files Used : - AAAR-Alfresco-CE-v5.2-Share-v4.5.amp  & AAAR-Alfresco-CE-v5.2-Repository-v4.5.amp
Pentaho :- pentaho-server-ce-7.0.0.0-25   & pdi-ce-7.0.0.0-25.zip

Issue :- Failed to Extract data regarding NODES . Please find the attached Screen Shot 
![AAAR_Error](https://user-images.githubusercontent.com/24791083/55551418-cb529100-56eb-11e9-95e0-6123205324e2.png)

We found that the Http Link using the Node Extraction was not fetching the content from the Alfresco  .I tried calling the Http link from the browser , it failed there as well .The Link came with the default AAAR installation is below .

http://192.168.10.131:8080/alfresco/service/AAAR/getNodesModifiedAfter?baseType=cm:content&dt=2001-01-01&customProperties={"types":[],"aspects":[]}&skip=0&limit=50000

However , when we change the link to below it the Http Link is working  . where we change "c" to capital letter in CustomProperties and removed the Dirac notation "{ }" from the CustomProperties  .

http://192.168.10.131:8080/alfresco/service/AAAR/getNodesModifiedAfter?baseType=cm:content&dt=2001-01-01&CustomProperties="types":[],"aspects":[]&skip=0&limit=50000

Requesting your help in getting the same fixed .

Please do find the log File for reference
[AAAR.log](https://github.com/fcorti/alfresco-audit-analysis-reporting/files/3043291/AAAR.log)
 .

Appreciate your effort in advance .

**Comment by fcorti** [comment]
Hi Shabanash,

Please use Afllystic instead of AAAR.
Alflytics is the newest major version of AAAR (with a new name).
You can find the documentation at the following link:
https://github.com/fcorti/Alflytics/blob/master/documentation/Alflytics-Manual.pdf
