### ISSUE TITLE
Issue in installing AAAR in Pentaho server

### ISSUE THREAD

**Issue by sneha-1111** [fcorti/alfresco-audit-analysis-reporting#53]
Hi Francesco,

I have been facing issue in installing AAAR in to the Pentaho server environment (CE Version 7.1). I have extended my alfresco with AAAR services,but when I try to access AAAR on alfresco, it gives page not found error. Also, I have downloaded pivot4j,saiku analytics and alflytics from marketplace but how to install them in to pentaho server to get AAAR dashboard on pentaho.
![11](https://user-images.githubusercontent.com/68941742/88770732-ddd3c200-d19b-11ea-9149-ac2b3afad336.png)
![12](https://user-images.githubusercontent.com/68941742/88770745-e2987600-d19b-11ea-83ab-9dba273cffc6.png)

**Comment by fcorti** [comment]
Instead of using AAAR, did you try with Alflytics?
(Alflytics is the evolution of AAAR)

http://fcorti.com/alflytics/

**Comment by sneha-1111** [comment]
Does it work for windows platform?I have installed Pentaho business analytics platform..but how to install alflytics through it?

**Comment by fcorti** [comment]
In principle it should work on Windows too, but it is suggested to use Linus based OS.
Please refer to the link above for all the info, documentation, links, etc.

**Comment by sneha-1111** [comment]
Hi,
I have followed the steps in the manual till now, but I am stuck at the the point- "updating the job to work with postgresql". I have installed pentaho data integration and it is connected to Alflytics repository. After this I am unable to locate jobs under ETL to update the default value of the parameter.

**Comment by fcorti** [comment]
Please look at the "Get all" job parameters.
You will find the parameter there.

**Comment by sneha-1111** [comment]
I am not able to locate Get all job under /public/Alflytics/ETL in pentaho data integration. Do we have to create it explicitly?
![di](https://user-images.githubusercontent.com/68941742/88923595-975f8f80-d28f-11ea-8138-be535582f809.png)

**Comment by fcorti** [comment]
Nope, it should be automatically imported from the installation wizard.
If not, the installation failed for some reason.
Do you have a log or something of the installation task?

**Comment by sneha-1111** [comment]
No ,I don't have log of data integration installation task,should I try reinstalling it?

**Comment by sneha-1111** [comment]
Hi,
I have reinstalled data integration but still unable to locate "Get all" job. I have installed data integration and Pentaho server both CE version 7.1. I am attaching log file of data integration.Do we need to run alfresco and pentaho server services simulatenously on tomcat?
[spoon (1).log](https://github.com/fcorti/alfresco-audit-analysis-reporting/files/5022213/spoon.1.log)

**Comment by fcorti** [comment]
Hi, 

From the log is pretty clear that the Pentaho installation is corrupted for some reason.
I recommend you help on properly install Pentaho, before going to AAAR/Alflytics.
To your point: Alfresco and Pentaho does not necessarily need to work on the same server.

**Comment by sneha-1111** [comment]
Hi,

Can you please suggest a manual/video for installing Pentaho server and Pentaho Data Integration precisely? I tried reinstalling it, but still getting the same issue.

**Comment by fcorti** [comment]
You can try this.

http://fcorti.com/2016/12/05/install-pentaho-business-analytics-platform-7/

**Comment by sneha-1111** [comment]
Hi,
I have reinstalled Pentaho server and Pentaho Data Integration and have also installed alflytics. What are the configuration settings for alflytics? and when we go to extract step on alflytics, how do we know the extraction is complete? attaching log 
[catalina.2020-08-18.log](https://github.com/fcorti/alfresco-audit-analysis-reporting/files/5089623/catalina.2020-08-18.log)
![configuration window](https://user-images.githubusercontent.com/68941742/90499169-d71ae800-e166-11ea-9676-a506d9dc0083.PNG)

And also, while running get all jobs on Pentaho Data Integration, I am getting the following error 
![get all job error](https://user-images.githubusercontent.com/68941742/90505123-bb680f80-e16f-11ea-99bf-5bb959ee40ca.PNG)

**Comment by fcorti** [comment]
Hello,

The log says that the Alflytics data schema is not installed (or available).
I think the installation task failed for some reasons.
Please repeat the installation task using the interface and check the log file before doing the extraction.

About your questions: checking the log file is always the correct thing to do.

On the parameters question: they should contain the proper parameters to point to the Alfresco instance.

**Comment by sneha-1111** [comment]
Hi,

I have reinstalled Alflytics and have installed Alflytics data schema. While I am extracting and generating the reports, the report says "no data available", is it because of no proper handshake between database and the pentaho server? Kindly, help me with establishing proper connections. I am attaching the log file and the necessary screenshots for your reference. 
[catalina (1).txt](https://github.com/fcorti/alfresco-audit-analysis-reporting/files/5124143/catalina.1.txt)
![check1](https://user-images.githubusercontent.com/68941742/91184602-719c9d80-e70a-11ea-8da4-47aadddc802b.PNG)
![reports error (1)](https://user-images.githubusercontent.com/68941742/91184620-77927e80-e70a-11ea-88c4-4146ac0fd914.png)

**Comment by fcorti** [comment]
Hi,

The error in the log file is clear: there is a connection problem between the Pentaho server/service and the Alfresco server/service.
Maybe there is a misconfiguration of the Alflytics.

**Comment by sneha-1111** [comment]
Hi,
I am trying to configure Alflytics, but if I try to save other than default configurations, it is giving me error and only default configurations could be saved successfully. Can you please help me with the correct alflytics configurations? attaching
[catalina.2020-08-26.log](https://github.com/fcorti/alfresco-audit-analysis-reporting/files/5130414/catalina.2020-08-26.log)
[alfresco global properties.txt](https://github.com/fcorti/alfresco-audit-analysis-reporting/files/5130438/alfresco.global.properties.txt)

 log and alfresco global properties file

**Comment by fcorti** [comment]
The user interface is simply filling the XML file at the path below:

https://github.com/fcorti/alfresco-audit-analysis-reporting/tree/master/Pentaho/AAAR-App-Pentaho-v7/endpoints/kettle/conf

You can manually set up the parameters directly in the XML file (in your Pentaho installation) and launch the Alflytics  installation again.

I hope it will help you.

**Comment by sneha-1111** [comment]
Hi,
I have tried locating those Xml files at the given path, but I am not able to locate them. Kindly, provide the path suitable with Alflytics. Attaching screenshots.
![config1](https://user-images.githubusercontent.com/68941742/91471576-ea8b2900-e8b3-11ea-9c0a-1071ea46f560.png)
![config3](https://user-images.githubusercontent.com/68941742/91471611-f0810a00-e8b3-11ea-8aab-769896154897.png)
![config4](https://user-images.githubusercontent.com/68941742/91471622-f4ad2780-e8b3-11ea-81ff-def50a4ac6fa.png)

**Comment by fcorti** [comment]
What you are (correctly) using is Alflytics, not AAAR.
They are different products.
I'll close this issue and please reopen it in the proper project.

https://github.com/fcorti/Alflytics

**Comment by fcorti** [comment]
PS: The manual at the link below has everything you need.
https://github.com/fcorti/Alflytics/blob/master/documentation/Alflytics-Manual.pdf
