### ISSUE TITLE
Issue in extracting data from Alflytics

### ISSUE THREAD

**Issue by sneha-1111** [fcorti/alfresco-audit-analysis-reporting#54]
Hello Francesco,
   
      I have been working on the project that requires alflytics for over a month now. I have following tools installed on my 
     Windows:

       1) Pentaho server (C.E 7.1)
       2) Alfresco ( C.E 5.2)
       3) PDI 
       4) Alflytics ( 5.0)

   I have followed the steps in the alflytics manual for installation. I have been facing the following issues:
       1) Getting error for few tasks in the extraction log
       2) Not able to view data quality log
       3) Error processing component/ no data found on the alflytics dashboard

While configuring alflytics, I have kept the configurations as default. In which files the configurations are saved? where should I locate those files? attaching log and the necessary screenshots for your reference.
![extraction11](https://user-images.githubusercontent.com/68941742/91799401-98942b80-ec44-11ea-98b5-a795c6f89fc9.png)
![no data1](https://user-images.githubusercontent.com/68941742/91799412-a184fd00-ec44-11ea-8e7b-fc3d1ce7173e.png)
[catalina.2020-08-31.log](https://github.com/fcorti/alfresco-audit-analysis-reporting/files/5154203/catalina.2020-08-31.log)

**Comment by fcorti** [comment]
Hi,

About the configurations, they are stored into the data base.
You can easily have access to it using a DB client.

If you need, I can create a contact with someone providing you the proper professional support (in this case write me at fcorti at gmail dot com).

As an Open Source project, it would be great if you could improve it solving issues and/or providing a better way to do tasks.

Let me know how it goes.

**Comment by sneha-1111** [comment]
Hi Francesco,
  I am working on Alflytics on windows platform. After I extract the data and check, it shows "no data available". Also, I am facing problem in saving configurations other than default ones. What could be the reason behind this? what can be done to make proper handshake between database and alflytics? attaching screenshots and catalina log for your reference.

[catalina.2020-11-26.log](https://github.com/fcorti/alfresco-audit-analysis-reporting/files/5606396/catalina.2020-11-26.log)
![alflytics dashboard](https://user-images.githubusercontent.com/68941742/100420880-40d35800-30ad-11eb-94f4-54cbd0e01ef2.png)
![alflytics check](https://user-images.githubusercontent.com/68941742/100420891-46c93900-30ad-11eb-82b4-5889de9c12f5.png)

**Comment by fcorti** [comment]
Hello,

In the catalina.log file I can see an error related to the SQL syntax.

`26-Nov-2020 11:05:07.062 SEVERE [http-apr-9113-exec-7] com.sun.jersey.spi.container.ContainerResponse.logException Mapped exception to response: 501
 javax.ws.rs.WebApplicationException: pt.webdetails.cda.dataaccess.QueryException: ERROR: function casewhen(boolean, unknown, unknown) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
  Position: 881`

I suspect you did not install Alflytics with the proper DB.
I suggest to follow the installation guide in all its steps.

I hope this helps you.
